import axios from "axios";
import { getCurrentUser } from "./authService";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

export async function generateApiKey({ name, email }) {
  try {
    const { data } = await axios.post(`${API_BASE_URL}/applicants/generate-key`, { name, email });
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to generate API key");
  }
}

export async function expireApiKey(id) {
  try {
    const { data } = await axios.post(`${API_BASE_URL}/applicants/${id}/expire-key`);
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to expire API key");
  }
}

export async function fetchApplicants() {
  try {
    const { data } = await axios.get(`${API_BASE_URL}/applicants`);
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to fetch applicants");
  }
}

export async function addApplicant({ name, email }) {
  try {
    const { data } = await axios.post(`${API_BASE_URL}/applicants`, { name, email });
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to add applicant");
  }
}

export async function addApplicantsBulk(applicants) {
  try {
    const { data } = await axios.post(`${API_BASE_URL}/applicants/bulk`, {
      applicants,
      generatedBy: getCurrentUser(),
    });
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to bulk-add applicants");
  }
}

export async function generateLink(id) {
  try {
    const { data } = await axios.post(`${API_BASE_URL}/applicants/${id}/generate-link`, {
      generatedBy: getCurrentUser(),
    });
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to generate link");
  }
}

export async function revokeLink(id) {
  try {
    const { data } = await axios.post(`${API_BASE_URL}/applicants/${id}/revoke-link`);
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to revoke link");
  }
}

export async function sendEmail(id, { subject, body }) {
  try {
    const { data } = await axios.post(`${API_BASE_URL}/applicants/${id}/send-email`, {
      subject,
      body,
    });
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to send email");
  }
}

export async function deleteApplicant(id) {
  try {
    await axios.delete(`${API_BASE_URL}/applicants/${id}`);
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to delete applicant");
  }
}

export async function fetchApplicantEvents(id) {
  try {
    const { data } = await axios.get(`${API_BASE_URL}/applicants/${id}/events`);
    return data;
  } catch (err) {
    throw new Error(err.response?.data?.error ?? "Failed to fetch applicant events");
  }
}

// Pure — no API call. Query param names must match CheckPage.jsx exactly (apiKey/name/email).
export function buildShareableLink({ apiKey, name, email }) {
  return `${window.location.origin}/check?apiKey=${encodeURIComponent(apiKey)}&name=${encodeURIComponent(name)}&email=${encodeURIComponent(email)}`;
}

const CSV_COLUMNS = [
  { key: "name", label: "Applicant Name" },
  { key: "email", label: "Email" },
  { key: "status", label: "Status" },
  { key: "generatedAt", label: "Link Generated Date" },
  { key: "apiKeyExpiresAt", label: "Link Expiration" },
  { key: "emailSentAt", label: "Email Sent Date" },
  { key: "emailResendCount", label: "Email Resent Count" },
  { key: "resultStatus", label: "Result Status" },
  { key: "resultDate", label: "Result Date" },
  { key: "generatedBy", label: "Generated By" },
  { key: "updatedAt", label: "Last Updated" },
];

// Module-level: eslint-plugin-react-hooks@7's purity rule flags Date.now() called from anywhere
// inside a component body, even inside a handler (see LESSONS.md) — kept out of ApplicantsPage.jsx.
const buildCsvFilename = () => `tcp-applicants-${Date.now()}.csv`;

const escapeCsvField = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`;

// Hand-rolled Blob+URL.createObjectURL export (no Papa Parse — not an approved dependency,
// CLAUDE_Supabase.md §2), same pattern as the old ResultsListPage.jsx.
export function exportApplicantsCsv(applicants) {
  const header = CSV_COLUMNS.map((column) => escapeCsvField(column.label)).join(",");
  const rows = applicants.map((applicant) => {
    const row = {
      ...applicant,
      resultStatus: applicant.result?.passFail ?? "",
      resultDate: applicant.result?.submittedAt ?? "",
    };
    return CSV_COLUMNS.map((column) => escapeCsvField(row[column.key])).join(",");
  });
  const csv = [header, ...rows].join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = buildCsvFilename();
  link.click();
  URL.revokeObjectURL(url);
}
