export const REQUIREMENTS_CONFIG = [
  {
    id: 1,
    name: "OS Version",
    type: "os",
    appliesToOS: "both",
    windowsMin: "Windows 10",
    macosMin: "macOS 12",
    maxValue: "",
    required: true,
    description: "Operating system version requirement.",
  },
  {
    id: 2,
    name: "CPU Cores",
    type: "cpu",
    appliesToOS: "both",
    windowsMin: "4",
    macosMin: "4",
    maxValue: "",
    required: true,
    description: "Minimum CPU core count.",
  },
  {
    id: 3,
    name: "RAM (GB)",
    type: "ram",
    appliesToOS: "both",
    windowsMin: "8",
    macosMin: "8",
    maxValue: "",
    required: true,
    description: "Minimum installed memory, in gigabytes.",
  },
  {
    id: 4,
    name: "Storage (GB)",
    type: "storage",
    appliesToOS: "both",
    windowsMin: "256",
    macosMin: "256",
    maxValue: "",
    required: true,
    description: "Minimum free storage capacity, in gigabytes.",
  },
  {
    id: 5,
    name: "Internet Down (Mbps)",
    type: "internet",
    appliesToOS: "both",
    windowsMin: "15",
    macosMin: "15",
    maxValue: "",
    required: true,
    description: "Minimum download speed, in Mbps.",
  },
  {
    id: 6,
    name: "Internet Up (Mbps)",
    type: "internet",
    appliesToOS: "both",
    windowsMin: "5",
    macosMin: "5",
    maxValue: "",
    required: true,
    description: "Minimum upload speed, in Mbps.",
  },
  {
    id: 7,
    name: "Screen Resolution",
    type: "screen",
    appliesToOS: "both",
    windowsMin: "1280x720",
    macosMin: "1280x720",
    maxValue: "",
    required: true,
    description: "Minimum screen resolution.",
  },
  {
    id: 8,
    name: "Webcam",
    type: "hardware",
    appliesToOS: "both",
    windowsMin: "Required",
    macosMin: "Required",
    maxValue: "",
    required: true,
    description: "Built-in or external webcam.",
  },
  {
    id: 9,
    name: "Headset",
    type: "hardware",
    appliesToOS: "both",
    windowsMin: "Required",
    macosMin: "Required",
    maxValue: "",
    required: true,
    description: "Built-in or external microphone and speakers/headphones.",
  },
];
