export const REQUIREMENTS_CONFIG = [
  // OS Version
  {
    id: 1,
    name: "OS Version",
    type: "os",
    appliesTo: "windows",
    minValue: "Windows 10",
    maxValue: "",
    required: true,
    description: "Operating system version requirement.",
  },
  {
    id: 2,
    name: "OS Version",
    type: "os",
    appliesTo: "macos",
    minValue: "macOS 12",
    maxValue: "",
    required: true,
    description: "Operating system version requirement.",
  },
  // CPU Cores
  {
    id: 3,
    name: "CPU Cores",
    type: "cpu",
    appliesTo: "windows",
    minValue: "4",
    maxValue: "",
    required: true,
    description: "Minimum CPU core count.",
  },
  {
    id: 4,
    name: "CPU Cores",
    type: "cpu",
    appliesTo: "macos",
    minValue: "4",
    maxValue: "",
    required: true,
    description: "Minimum CPU core count.",
  },
  // RAM (GB)
  {
    id: 5,
    name: "RAM (GB)",
    type: "ram",
    appliesTo: "windows",
    minValue: "8",
    maxValue: "",
    required: true,
    description: "Minimum installed memory, in gigabytes.",
  },
  {
    id: 6,
    name: "RAM (GB)",
    type: "ram",
    appliesTo: "macos",
    minValue: "8",
    maxValue: "",
    required: true,
    description: "Minimum installed memory, in gigabytes.",
  },
  // Storage (GB)
  {
    id: 7,
    name: "Storage (GB)",
    type: "storage",
    appliesTo: "windows",
    minValue: "256",
    maxValue: "",
    required: true,
    description: "Minimum free storage capacity, in gigabytes.",
  },
  {
    id: 8,
    name: "Storage (GB)",
    type: "storage",
    appliesTo: "macos",
    minValue: "256",
    maxValue: "",
    required: true,
    description: "Minimum free storage capacity, in gigabytes.",
  },
  // Internet Down (Mbps)
  {
    id: 9,
    name: "Internet Down (Mbps)",
    type: "internet",
    appliesTo: "windows",
    minValue: "15",
    maxValue: "",
    required: true,
    description: "Minimum download speed, in Mbps.",
  },
  {
    id: 10,
    name: "Internet Down (Mbps)",
    type: "internet",
    appliesTo: "macos",
    minValue: "15",
    maxValue: "",
    required: true,
    description: "Minimum download speed, in Mbps.",
  },
  // Internet Up (Mbps)
  {
    id: 11,
    name: "Internet Up (Mbps)",
    type: "internet",
    appliesTo: "windows",
    minValue: "5",
    maxValue: "",
    required: true,
    description: "Minimum upload speed, in Mbps.",
  },
  {
    id: 12,
    name: "Internet Up (Mbps)",
    type: "internet",
    appliesTo: "macos",
    minValue: "5",
    maxValue: "",
    required: true,
    description: "Minimum upload speed, in Mbps.",
  },
  // Screen Resolution
  {
    id: 13,
    name: "Screen Resolution",
    type: "screen",
    appliesTo: "windows",
    minValue: "1280x720",
    maxValue: "",
    required: true,
    description: "Minimum screen resolution.",
  },
  {
    id: 14,
    name: "Screen Resolution",
    type: "screen",
    appliesTo: "macos",
    minValue: "1280x720",
    maxValue: "",
    required: true,
    description: "Minimum screen resolution.",
  },
  // Webcam
  {
    id: 15,
    name: "Webcam",
    type: "hardware",
    appliesTo: "windows",
    minValue: "Required",
    maxValue: "",
    required: true,
    description: "Built-in or external webcam.",
  },
  {
    id: 16,
    name: "Webcam",
    type: "hardware",
    appliesTo: "macos",
    minValue: "Required",
    maxValue: "",
    required: true,
    description: "Built-in or external webcam.",
  },
  // Headset
  {
    id: 17,
    name: "Headset",
    type: "hardware",
    appliesTo: "windows",
    minValue: "Required",
    maxValue: "",
    required: true,
    description: "Built-in or external microphone and speakers/headphones.",
  },
  {
    id: 18,
    name: "Headset",
    type: "hardware",
    appliesTo: "macos",
    minValue: "Required",
    maxValue: "",
    required: true,
    description: "Built-in or external microphone and speakers/headphones.",
  },
];
