import { useEffect, useRef, useState } from "react";
import { fetchApplicantEvents } from "../../services/applicantsService";
import { parseDbTimestamp } from "../../utils/dateTime";

function formatDateTime(value) {
  const date = parseDbTimestamp(value);
  return date ? date.toLocaleString() : "—";
}

// Same field TestResultModal shows as result.submittedAt — kept in Eastern Time here too so
// the two views of the same submission never disagree on what time it happened.
// Intl.DateTimeFormat throws if dateStyle/timeStyle are mixed with individual field options
// like timeZoneName, so this spells out the fields instead of using the style shorthand.
function formatResultTime(value) {
  const date = parseDbTimestamp(value);
  if (!date) return "—";
  return date.toLocaleString("en-US", {
    timeZone: "America/New_York",
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    timeZoneName: "short",
  });
}

function formatEventType(eventType) {
  if (!eventType) return "Unknown event";
  const words = eventType.replaceAll("_", " ");
  return words.charAt(0).toUpperCase() + words.slice(1);
}

// details is a free-form JSON blob from the API (event-specific: expires_at, sent_to,
// result_status, etc.) — rendered generically instead of hard-coding key names, since the
// exact shape is owned by BB2's backend implementation, not this file.
function formatEventDetails(details) {
  if (!details || typeof details !== "object") return "";
  const parts = Object.entries(details)
    .filter(([, value]) => value !== null && value !== undefined && value !== "")
    .map(([key, value]) => `${key}: ${value}`);
  return parts.length > 0 ? ` (${parts.join(", ")})` : "";
}

function EventList({ events }) {
  if (events.length === 0) {
    return <p className="text-sm text-gray-500">No events yet.</p>;
  }
  return (
    <ul className="mb-4 space-y-1 text-sm text-gray-700">
      {events.map((event) => (
        <li key={`${event.eventType}_${event.createdAt}`}>
          <span className="font-medium">{formatEventType(event.eventType)}</span>
          {" — "}
          {formatDateTime(event.createdAt)}
          {formatEventDetails(event.details)}
        </li>
      ))}
    </ul>
  );
}

// Fetches applicant events once per row on first expand and keeps the result in this
// component's own state; ApplicantRow keeps this component mounted (hidden, not unmounted)
// after the first expand so re-collapsing/re-expanding never re-fetches. `fetchStarted` is a
// ref (not state) so the effect never calls a setState function synchronously in its body —
// this repo's react-hooks/set-state-in-effect lint rule flags that pattern; `loading` is
// derived from `events`/`error` during render instead of tracked as its own state.
function ApplicantHistory({ applicant, expanded }) {
  const [events, setEvents] = useState(null);
  const [error, setError] = useState(null);
  const fetchStarted = useRef(false);

  useEffect(() => {
    if (!expanded || fetchStarted.current) return;
    fetchStarted.current = true;
    fetchApplicantEvents(applicant.id)
      .then(setEvents)
      .catch((err) => setError(err.message));
  }, [expanded, applicant.id]);

  const loading = expanded && events === null && error === null;

  return (
    <div className="bg-gray-50 px-6 py-4">
      {loading && <p className="text-sm text-gray-500">Loading history…</p>}
      {error && <p className="text-sm text-red-600">{error}</p>}
      {events && <EventList events={events} />}
      <div className="grid grid-cols-1 gap-1 text-sm text-gray-600 sm:grid-cols-3">
        <p>Generated by: {applicant.generatedBy ?? "—"}</p>
        <p>First email sent: {formatDateTime(applicant.emailSentAt)}</p>
        <p>Result date: {formatResultTime(applicant.result?.submittedAt)}</p>
      </div>
    </div>
  );
}

export default ApplicantHistory;
